# Generated by Django 3.1.7 on 2021-02-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatApp',
        ),
    ]
