# Generated by Django 3.1.7 on 2021-02-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
