# Generated by Django 3.1.7 on 2021-02-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_auto_20210227_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='owner',
        ),
    ]
