# Generated by Django 3.1.7 on 2021-02-27 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_message_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='owner',
            new_name='user',
        ),
    ]
