# Generated by Django 3.1.7 on 2021-02-28 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0013_auto_20210228_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomname',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='text',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
