# Generated by Django 3.1.7 on 2021-03-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0014_auto_20210228_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='text',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.room'),
        ),
    ]
