# Generated by Django 3.1.7 on 2021-03-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0015_auto_20210306_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomname',
        ),
    ]
