# Generated by Django 3.1.7 on 2021-03-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0017_auto_20210306_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomname',
        ),
        migrations.AddField(
            model_name='message',
            name='roomname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='text',
            field=models.CharField(default=True, max_length=255, null=True),
        ),
    ]
