# Generated by Django 3.1.7 on 2021-03-06 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0018_auto_20210306_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='channel',
        ),
    ]
