# Generated by Django 3.1.7 on 2021-03-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0019_remove_message_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='text',
            new_name='roomname',
        ),
    ]
