# Generated by Django 3.1.7 on 2021-03-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0020_auto_20210306_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='roomname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
