# Generated by Django 3.1.7 on 2021-03-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0023_room_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='text',
        ),
    ]
